
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/desertbit/glue"
  version = "1.9.1"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/facebookgo/inject"

[[constraint]]
  branch = "master"
  name = "github.com/getsentry/raven-go"

[[constraint]]
  branch = "master"
  name = "github.com/gin-gonic/contrib"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/goinggo/work"

[[constraint]]
  branch = "master"
  name = "github.com/henrylee2cn/goutil"

[[constraint]]
  branch = "master"
  name = "github.com/hjr265/postmark.go"

[[constraint]]
  name = "github.com/kennygrant/sanitize"
  version = "1.2.3"

[[constraint]]
  name = "github.com/markbates/goth"
  version = "1.44.1"

[[constraint]]
  name = "github.com/mikespook/gorbac"
  version = "2.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/goamz"

[[constraint]]
  branch = "master"
  name = "github.com/olebedev/config"

[[constraint]]
  name = "github.com/op/go-logging"
  version = "1.0.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.3"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  branch = "master"
  name = "github.com/tidwall/buntdb"

[[constraint]]
  branch = "master"
  name = "github.com/xuyu/goredis"

[[constraint]]
  branch = "master"
  name = "golang.org/x/text"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/abiosoft/ishell.v2"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"

[[constraint]]
  name = "github.com/hjson/hjson-go"
  version = "3.0.0"

[[constraint]]
  name = "github.com/imdario/mergo"
  version = "0.3.2"
